eureka:
  instance:
   hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:

    
        - id: Customer_Service
          uri: http://localhost:8084/
          predicates:
            - Path=/api/v2/**
